### ISSUE TITLE
Chainloader version doesn't work with the latest AMS 0.19.2

### ISSUE THREAD

**Issue by JrRadiant** [averne/Fizeau#27] opened 2021-05-01 06:19 UTC
Hi!

The subj is -- chainloader version doesn't work with the latest AMS 0.19.2. It was all good on AMS 0.19.1, but doesn't work with the latest one, AMS 0.19.2

Please fix. :)

Thanks in advance!

**Comment by averne** [comment] 2021-05-01 10:14
Works for me, but this was probably due to a check on the AMS api version that I just removed.
Can you if it crashes now?
[Fizeau-chl-2.1.6-efb8092.zip](https://github.com/averne/Fizeau/files/6409370/Fizeau-chl-2.1.6-efb8092.zip)

**Comment by JrRadiant** [comment] 2021-05-01 13:57
Hi!..

With this version, AMS 0.19.2 and FW 12.0.1 it's still the same panic error with 010000000000CF12 titleid when system starts. When I remove 010000000000CF12 folder, it's loading good.

**Comment by averne** [comment] 2021-05-01 14:05
Could you upload the error report?
Everything works fine over here, so make sure to run the hekate bit fixer, see if there's no missing file, etc

**Comment by JrRadiant** [comment] 2021-05-01 14:15
> Everything works fine over here
You've the same MS 0.19.2 + FW 12.0.1 and it's all good for you?..

Hmm! Here's the crashlog: 
[report_0aaea971.zip](https://github.com/averne/Fizeau/files/6409702/report_0aaea971.zip)

```
PANIC error occured while running Atmosphere.
TitleID 010000000000CF12
Error std::abort (0xFFE)
Press power to continue.
```

With AMS 0.19.1 it was all good though.

**Comment by averne** [comment] 2021-05-01 15:22
> You've the same AMS 0.19.2 + FW 12.0.1 and it's all good for you for now?..
![2021050117031600-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/45773016/116786858-4809f200-aaa1-11eb-8bff-99166ddc81ac.jpg)

According to your error report the chainloader fails to launch the main program, or to initialize the `fizeau` service, which makes little sense...

**Comment by JrRadiant** [comment] 2021-05-01 15:28
Maybe I can do something more for help?

**Comment by averne** [comment] 2021-05-01 15:31
Are you using mesophere or the official kernel?
I guess you could try reproducing on a clean SD.

**Comment by JrRadiant** [comment] 2021-05-01 15:39
Yep, AMS with mesosphere (M).

Maybe you can upload the new non-chainloader 2.6 version to test it in HOS?..

With Fizeau-2.1.5-d35dfa8 (non-chainloader) version the system boots OK, but I've got this error:
![2021050121352200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/61790774/116787424-bcef2300-aac5-11eb-8b03-3e624fd4ad6a.jpg)

**Comment by averne** [comment] 2021-05-01 15:55
Here you go: [Fizeau-2.1.6-efb8092.zip](https://github.com/averne/Fizeau/files/6409855/Fizeau-2.1.6-efb8092.zip)
That means the service is registered but not responding somehow.

**Comment by JrRadiant** [comment] 2021-05-01 16:25
Thanks! With the new Fizeau-2.1.6 it's still the same error..

> That means the service is registered but not responding somehow.

If it's only my problem that's OK, I'll try to figure it out.

If anybody has that problem, too, please respond!

**Comment by Parnassius** [comment] 2021-05-01 17:11
Hi, I'm experiencing the same problem. Fizeau-chl-2.1.5 works fine with Atmosphere-0.19.1, crashes on boot with Atmosphere-0.19.2 (both with Mesosphere).
Removing the chainloader folder the system boots, but opening Fizeau.nro yields the same result shown above by JrRadiant, I tried both 2.1.5 and the 2.1.6 attached above.
I'll try if I can reproduce this using a clean sd card soon-ish.

**Comment by Parnassius** [comment] 2021-05-01 17:23
Using a clean sd (aside from other unrelated files) with latest Atmosphere (with Mesosphere) and latest Hekate (to chainload fusee-primary, not sure if this is relevant):
- Fizeau-chl-2.1.5: crashes on boot, same as above
- Fizeau-2.1.5: system boots, opening Fizeau.nro shows the same error as above
- Fizeau-2.1.6: system boots, opening Fizeau.nro shows the same error as above

**Comment by JrRadiant** [comment] 2021-05-01 17:36
@Parnassius The same errors, yeah.
You can also try Fizeau-chl-2.1.6-efb8092.zip from here: https://github.com/averne/Fizeau/files/6409370/Fizeau-chl-2.1.6-efb8092.zip doesn't work for me on AMS M.19.2, too.

**Comment by Parnassius** [comment] 2021-05-01 17:52
Small correction: I just noticed that the title id shown in the fatal screen is 0100000000000f12, _not_ 010000000000cf12, both using Fizeau-chl-2.1.5 and Fizeau-chl-2.1.6. I'm attaching the fatal report generated while trying with Fizeau-chl-2.1.6.
[report_0000000009f35935.zip](https://github.com/averne/Fizeau/files/6410055/report_0000000009f35935.zip)

@averne please let us know if there's anything more we can do to help

**Comment by averne** [comment] 2021-05-01 18:05
> Small correction: I just noticed that the title id shown in the fatal screen is 0100000000000f12, _not_ 010000000000cf12, both using Fizeau-chl-2.1.5 and Fizeau-chl-2.1.6. I'm attaching the fatal report generated while trying with Fizeau-chl-2.1.6.
> [report_0000000009f35935.zip](https://github.com/averne/Fizeau/files/6410055/report_0000000009f35935.zip)
> 
> @averne please let us know if there's anything more we can do to help

Thanks for testing, I can reproduce by booting via fusee-primary instead of my usual hekate.

**Comment by averne** [comment] 2021-05-01 18:19
Should be fixed:
[Fizeau-chl-2.1.6-efb8092-dirty.zip](https://github.com/averne/Fizeau/files/6410090/Fizeau-chl-2.1.6-efb8092-dirty.zip)

[Fizeau-2.1.6-efb8092-dirty.zip](https://github.com/averne/Fizeau/files/6410088/Fizeau-2.1.6-efb8092-dirty.zip)

**Comment by JrRadiant** [comment] 2021-05-01 18:23
Fizeau-chl-2.1.6-efb8092-dirty tested and it works good — thank you very much for fast, professinal and friendly support!..

**Comment by Parnassius** [comment] 2021-05-01 18:24
I can confirm the -chl- zip works fine here as well, thanks a lot!

**Comment by averne** [comment] 2021-05-01 18:59
Thanks everyone, closing.

**Closed by averne** 2021-05-01 18:59 UTC
