### ISSUE TITLE
14.0.0 update fizeau crash on launch

### ISSUE THREAD

**Issue by azammm786** [averne/Fizeau#49] opened 2022-03-30 15:32 UTC
Fizeau is making atmosphere crash on boot, I have downloaded latest build but when i open the overlay it just goes back to tesla menu the overlay doesnt appear, any way to fix

**Comment by threethan** [comment] 2022-04-04 05:33
Since this isn't the most descriptive I'll describe what I think is the same issue.
Using Fizeau 2.3.0, I cannot boot with the Fizeau sysmodule installed.

Removing atmosphere/contents/0100000000000F12 allows the device to boot, but (obviously) causes the Fizeau overlay to no longer launch.

Image of error screen when booting with Fizeau sysmodule:
![image](https://user-images.githubusercontent.com/12588584/161479666-6ae9198e-b2ec-4205-9f72-3e667c9a2cb4.png)

**Comment by azammm786** [comment] 2022-04-04 08:29
Unfortunately ive tried both versions you have provided. one results in what threethan showed above and the other just boots into atmosphere with a black lit up screen. is there anyway to get it to work in the meantime?

**Comment by carr654** [comment] 2022-04-05 19:43
> Hi, it's a known issue that happens because 14.0 changed some stuff. I still need to properly update the code, in the meantime this should work https://github.com/averne/Fizeau/suites/5792173064/artifacts/193335586

this worked great thank you so much as its the reason why i didnt update to 14.0 straight away

**Comment by azammm786** [comment] 2022-04-06 07:03
> > Hi, it's a known issue that happens because 14.0 changed some stuff. I still need to properly update the code, in the meantime this should work https://github.com/averne/Fizeau/suites/5792173064/artifacts/193335586
> 
> this worked great thank you so much as its the reason why i didnt update to 14.0 straight away

How did you get this to work please?

**Comment by carr654** [comment] 2022-04-06 17:21
> > > Hi, it's a known issue that happens because 14.0 changed some stuff. I still need to properly update the code, in the meantime this should work https://github.com/averne/Fizeau/suites/5792173064/artifacts/193335586
> > 
> > 
> > this worked great thank you so much as its the reason why i didnt update to 14.0 straight away
> 
> How did you get this to work please?

i just used the file that was send by dev above and it worked for me i just gone into the zip for me i like the chainloader one so gone into that folder and just copied over the atmos etc folders to sd card and done it just works, the backlight on the overlay and in app have been disabled but i just use the nintendo home button for that so aint the end of the world

**Comment by averne** [comment] 2022-11-01 12:46
Closing as duplicate of #48

**Closed by averne** 2022-11-01 12:46 UTC
